### ISSUE TITLE
Branch protection out of compliance even tough codereview requirements is set to 1

### ISSUE THREAD

**Issue by godofredoc** [ossf/allstar#116]
Dart and Flutter Orgs branch protection requires 1 codereview but we allow some bot accounts to bypass the requirement. This is causing the allstar application to detect that the repositories as out of compliance:

```
Allstar has detected that this repository’s Branch Protection security policy is out of compliance. Status:
PR Approvals not configured for branch master
```

Could this be related to https://github.com/ossf/scorecard/issues/1614?

**Comment by jeffmendoza** [comment]
Which repo? I'll check the logs. I can also test what we get from a test repo.

Allstar uses a different API than scorecard (rest, not graphql). Also it is an App, and not a user (PAT/Oauth), so it shouldn't be related to the scorecard issue.

@Hixie are you seeing this across all Flutter?

**Comment by Hixie** [comment]
@godofredoc which repo are you seeing this on?
The only flutter repos I see branch protection being called out on are private ones (because we don't have the Enterprise plan so we can't make those secure) and archived ones (because of https://github.com/ossf/allstar/issues/108).

**Comment by godofredoc** [comment]
I found those bugs last Friday but looking again today they are now closed. I believe we can close this issue, thanks for investigating.
