### ISSUE TITLE
Add ability to ignore certain files in Binary Artifacts policy

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/allstar#157]
Scorecards returns a list of artifacts. We can just filter the list and if the resulting list is len=0 then pass the policy.

Eventually we will pass this ignore list to scorecards which will incorporate in the returned score.

**Comment by jeffmendoza** [comment]
Ideally we would like scorecards to handle well-known binaries, and allow them if the repo follows best practices for those binaries. Ex:
https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification
https://github.com/marketplace/actions/gradle-wrapper-validation

> The gradle-wrapper.jar is a binary blob of executable code that is checked into nearly [2.8 Million GitHub Repositories](https://github.com/search?l=&q=filename%3Agradle-wrapper.jar&type=Code).

> As with all such files, you should be sure that it’s trustworthy before executing it. Since the Wrapper JAR is usually checked into a project’s version control system, there is the potential for a malicious actor to replace the original JAR with a modified one by submitting a pull request that seemingly only upgrades the Gradle version.

**Comment by david-a-wheeler** [comment]
it should be possible for a project to list ones it knows about, just like .gitignore.

Maybe allow a top-level file list:
.artifact-ignore
and remove those files.
False positives are a common tool problem, we need a simple solution for them.

**Comment by jeffmendoza** [comment]
General consensus was "+1" in the sync meeting

> Maybe allow a top-level file list:
.artifact-ignore

I'd be more inclined to include the ignore list in the existing allstar config, with allowing it at the org-level `binary_artifacts.yaml`, and then allowing repo-override in the repo `.allstar/binary_artifacts.yaml` file.

**Comment by azeemshaikh38** [comment]
> I'd be more inclined to include the ignore list in the existing allstar config, with allowing it at the org-level `binary_artifacts.yaml`, and then allowing repo-override in the repo `.allstar/binary_artifacts.yaml` file.

+1 to this. This aligns well with how users interact with AllStar today.

**Comment by jeffmendoza** [comment]
Fixed with #176
