### ISSUE TITLE
False positive from binary file detection

### ISSUE THREAD

**Issue by daviddrysdale** [ossf/allstar#173]
See https://github.com/google/capsicum-linux/issues/12 &ndash; although the file has a `.lib` suffix, it's not a binary file.

Note that this particular false positive will potentially be reported for every fork of the [Linux kernel](https://github.com/torvalds/linux/blob/master/scripts/Makefile.lib).

**Comment by jeffmendoza** [comment]
Thanks for reporting @daviddrysdale I've opened https://github.com/ossf/scorecard/issues/1868

**Comment by daviddrysdale** [comment]
Ah, I got the wrong repo, sorry &ndash; thanks for relocating.
