### ISSUE TITLE
Proposal: Individual repo config in org config repo

### ISSUE THREAD

**Issue by yorinasub17** [ossf/allstar#186]
## Problem

In our org, we would like to restrict access to the Allstar configurations as much as possible, which means that we want to set `disableRepoOverride = true` for all the policies. However, this leaves a problem where the settings for Allstar must be all or nothing - that is, we can only have one configuration for all the repos, or none at all.

This proves a challenge for the branch protection settings, where some repos have additional checks that we would like to enforce, and want to use Allstar to ensure those settings stay on. If we had repo level config, this can be handled by adding a `.allstar` folder and config in the underlying repos, but then this means that developers of the repo can turn Allstar checks off if they wanted to (e.g., set `action: log`), which we would like to avoid.

This is a request for a mechanism that allows configuring individual repo overrides in the org level `.allstar` repo.

## Solution

The proposed solution is to allow configuring individual repo overrides from the org `.allstar` repo by introducing each individual repo config as folders.

Consider the following proposed folder tree for a `.allstar` repo:

```
├── README.md
├── allstar.yaml
├── binary_artifacts.yaml
├── branch_protection.yaml
├── dangerous_workflow.yaml
├── outside.yaml
├── security.yaml
├── myapp
│   └── branch_protection.yaml
└── someotherapp
    ├── dangerous_workflow.yaml
    └── outside.yaml
```

In this tree, the global org level config is defined in the root `yaml` files as before. However, in this proposal, we also introduce individual repo folders, such as `myapp` and `someotherapp`, whose configurations will act as repo level configurations that can override the org level config.

In this example, `myapp/branch_protection.yaml` will be merged up with `binary_protection.yaml` to produce the final config.

Note that if `disableRepoOverride = false` and there exists a `.allstar/branch_protection.yaml` file in the `myapp` repo, then that will have precedence over `myapp/branch_protection.yaml`.

So the order of look up will be:

1. `myapp` repo  `.allstar/branch_protection.yaml`
2. org `.allstar` repo `myapp/branch_protection.yaml`
3. org `.allstar` repo `branch_protection.yaml`

---

If this solution seems reasonable, I'd be happy to work on a PR to implement this!

**Comment by jeffmendoza** [comment]
This sounds very reasonable! All the priority logic you describe sounds great.

Just thinking, we might end up wanting to change `EnforceBranches` in the org level branch protection to just be a single list in this case. We can tackle that later though, as we will need to deprecate the existing setting.

**Comment by yorinasub17** [comment]
Thanks for the confirmation! Took a stab at an implementation in https://github.com/ossf/allstar/pull/192

**Comment by yorinasub17** [comment]
> Just thinking, we might end up wanting to change EnforceBranches in the org level branch protection to just be a single list in this case. We can tackle that later though, as we will need to deprecate the existing setting.

I'd love to know more about this, because I think it relates to another feature I wanted to propose, but I don't have enough context on this setting to know the intention. Do you mean that you want to change it so that `EnforceBranches` is not always overridden regardless of `disableRepoOverride`?

If so, then that would be great, because I think with that, we can optimize the config fetch routine to avoid attempting to fetch the repo configs if `disableRepoOverride = true`. This will save 1 API call per repo, which would be a big help in further addressing https://github.com/ossf/allstar/issues/170
