### ISSUE TITLE
Kicad .lib files are considered "Binary Artifacts"

### ISSUE THREAD

**Issue by thatch** [ossf/allstar#200]
I got filed three issues on repositories that contain kicad files.  These are all false-positives, and the files are clearly not executable.

https://github.com/google/makerspace-lipo-charger/issues/1
https://github.com/google/makerspace-auth/issues/47
https://github.com/google/makerspace-partsbin/issues/19

**Comment by jeffmendoza** [comment]
The fix in scorecard: https://github.com/ossf/scorecard/pull/1879 was pulled in with #213 fixing this.
