### ISSUE TITLE
allstar is spamming my repo - exemption instructions are hidden

### ISSUE THREAD

**Issue by randomascii** [ossf/allstar#227]
Allstar keeps spamming my repo with warnings about binary artifacts with no accountability. There is no way to opt out, ask for exemptions, or do anything other than comply with the demands or mark the email as spam.

The issue in question is this one: https://github.com/google/UIforETW/issues/155

Some of the binary files could be avoided because they are generated from the source-code in the repo (which also makes them less dangerous), but others cannot. dbghelp.dll and pdbcopy.exe are copied from Microsoft SDKs. Removing them from the repo would make releases _less_ secure since the release process would have to depend on whatever copies of these files the release packager happens to have on their machines.

I have little incentive to remove the binary files that I could remove because I'll still get exactly the same number of pings on this issue. I think there needs to be a process for opting out or saying "I've looked at these binary artifacts and I have chosen to keep them because X, Y, and Z"

P.S. While writing this issue I found the discussion about enforcement exemptions. I think I missed it before because the link is broken. The link target is https://g3doc.corp.google.com/company/teams/opensource/github/allstar.md?cl=head#FAQ but the page does not move when the link is clicked. I'm using the latest version of Chrome on desktop. That should be fixed.

**Comment by randomascii** [comment]
P.S. The FAQ link in the address bar works, but the on in the body of the page doesn't work. This is the page I am looking at:

https://g3doc.corp.google.com/company/teams/opensource/github/allstar.md?cl=head

Clicking on "Please see the [FAQ](https://g3doc.corp.google.com/company/teams/opensource/github/allstar.md?cl=head#FAQ) for exemption options." does not work.

Clicking on [FAQ](https://g3doc.corp.google.com/company/teams/opensource/github/allstar.md?cl=head#faq) (in the page contents sidebar on the right) does work.

It looks like upper-case versus lower-case matters.

**Comment by randomascii** [comment]
Updating issue after ping interval. Status:

The FAQ link is still broken.

**Comment by jeffmendoza** [comment]
Internal doc link fixed.

Project docs are: https://github.com/ossf/allstar#disabling-unwanted-issues-1  https://github.com/ossf/allstar/blob/main/opt-out.md

**Comment by randomascii** [comment]
I know (from looking at the internal docs) that the answer is in the FAQ, but I can't find a FAQ in the public repo.

I know from looking at the FAQ that the solution is to add an ignorePaths entry to a .allstar/binary_artifacts.yaml file but I can find no reference to that in the public documentation. Are the ignorePaths instructions supposed to be secret?
