### ISSUE TITLE
Signed files should be exempt from warnings

### ISSUE THREAD

**Issue by randomascii** [ossf/allstar#243]
My github project necessarily contains five binary files that come from a Microsoft SDK. They are needed for proper operation of the project. Removing them from the repo would require getting them from somewhere else which would be _less_ secure.

These files are all signed. The allstar project could reduce it's "false positive" rate by treating signed files separately, either not warning on them or giving a different type of warning.

Right now if I add a signed binary file to my repo the warning will be identical to the warning I get when I add an unsigned file, despite the fact that the risk level is dramatically different between the two of them. This means that I have to do manual signature checking, which is something that allstar should be doing.

**Comment by jeffmendoza** [comment]
Thanks for the suggestion, I've opened an issue on scorecards.
