### ISSUE TITLE
ignorePaths directive and binary_artifacts.yaml file are not documented

### ISSUE THREAD

**Issue by randomascii** [ossf/allstar#244]
Either the ignorePaths directive and the binary_artifacts.yaml file which contains it are not documented or they are hidden too well. I find them in some internal Google documentation (which is how I managed to create this file: https://github.com/google/UIforETW/blob/main/.allstar/binary_artifacts.yaml) but they do not appear to be publicly documented.

**Comment by jeffmendoza** [comment]
The policy doc section https://github.com/ossf/allstar#binary-artifacts links to the config definitions https://pkg.go.dev/github.com/ossf/allstar/pkg/policies/binary#OrgConfig with the detailed config documentation. It is a priority for us to complete the policy docs, covered in #62
