### ISSUE TITLE
[Proposal] Action Use Policy

### ISSUE THREAD

**Issue by ghost** [ossf/allstar#246]
# Proposal: Allstar Action Use Policy

## Context

An Allstar policy should allow GitHub organization security managers to control the use of Actions within their organizations. This policy should provide highly granular configuration options to support many use cases and provide insightful issue text to make reaching compliance easy for repo maintainers.

## Background

GitHub provides hosted CI for repos using a system called "Actions", in which "workflows" are defined as sets of jobs and the circumstances in which to run them. Each job can contain steps, which each might execute an Action or run a command. Actions can perform tasks and checks. Repos can include workflows by including them in their .github/workflows directory. ([Workflow file spec](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions))

Currently, organizations don't have the ability to require the use of Actions within their repos, and limited ability to configure Action allowlists. (Currently, GitHub does provide an allowlist feature, but it does not support semver constraint checking, only glob match.)

Some organizations may be interested in requiring the use of Actions. [A proposal](https://github.com/slsa-framework/slsa/issues/424) in SLSA, for example, would require SCA, SAST, and DAST vulnerability checking for all repos. Yet there isn't a way to enforce these requirements at the organization level currently.

### Brief Overview

The policy boils down to a list of rules at the organization level. The rules can be used to achieve Action allowlist or blocklist-style policies, and define which Actions are required.

For the [SLSA proposal](https://github.com/slsa-framework/slsa/issues/424), there are a number of Actions that could potentially satisfy each of the first three requirements, and so the solution should provide a method of requiring a defined number of Actions in a set (in fact, multiple sets) to be present.

![Action Use Policy 1 drawio](https://user-images.githubusercontent.com/14060354/183601412-a0d6025d-8eef-40b7-ad94-687463174326.png)

Furthermore, there should be an additional option which can be used to require that the Actions specified are "passing" (or more specifically, part of a passing workflow) in the latest commit. This way, projects ignoring failed required actions will fail the policy as well.

Also, it makes sense to allow targeting of repos because not all Action use rules will apply to all of an organization's repos. Repos should be able to be targeted by name and by content. Specifically, targeting by at least language makes sense.
Additionally, the policy should create warnings sufficiently detailed for an engineer unfamiliar with Allstar to understand. To that end, each rule should have a name describing its purpose.

Putting it all together, an organization-level configuration just implementing the SAST rule described above might look like this:

```yaml
groups:
  - name: "All repos"
    # target all repos
    # not including the group repo field would also select all repos
    repos:
      - name: "*"
    rules:
      - name: "Require a passing DAST Action for all repos"

        # See "Order and means of Rule evaluation" and field comment
        # for Rule struct.
        priority: high

        # require at least count of the listed Actions to be present
        method: require

        # default count is number of listed Actions
        # in this case, only one of the listed actions is required to pass
        count: 1

        # the Action must be "passing" in the latest commit
        mustPass: true

        actions:
          - name: "stackhawk/hawkscan-action"
            version: ">= 2.0.0"
          - name: "projectdiscovery/nuclei-action"
            # Non-semver versions will check for a commit ref / commit hash
            version: "main"
```

### Struct: OrgConfig, RuleGroup, and Rule

This configuration should be specified at the org level only.

```go
// OrgConfig is the org-level configuration
type OrgConfig struct {
  // Note that there is no config.OrgOptConfig field. This is because
  // allowing opt-out with an OrgOptConfig would be redundant and could
  // confuse users.

  // Groups is the set of RuleGroups to employ during Check.
  // They are evaluated in order.
  Groups []*RuleGroup `json:"groups"`
}

// RuleGroup is used to apply rules to repos matched by RepoSelectors.
type RuleGroup struct {
  // Name is the name used to identify the RuleGroup.
  Name string

  // Repos is the set of RepoSelectors to use when deciding whether
  // a repo qualifies for this RuleGroup.
  // If nil, select all repos.
  Repos []*RepoSelector

  // Rules is the set of rules to apply for this RuleGroup.
  // They are applied in order.
  Rules []*Rule
}

// Rule is an Action Use rule
type Rule struct {
  // Name is the rule's name
  // Preferred format begins with an imperative verb, eg. "Require"
  Name string

  // Method is a string, one of "require", "allow", and "deny"
  Method string

  // Priority is the priority tier identifier applied to the rule.
  // Options are "urgent", "high", "medium", and "low"
  Priority string

  // Actions is a set of ActionSelectors.
  // If nil, all Actions will be selected
  Actions []*ActionSelector

  // MustPass specifies whether the rule's Action(s) are required to
  // be part of a passing workflow on latest commit.
  // [For use with "require" method]
  MustPass bool

  // RequireAll specifies that all Actions listed should be required,
  // rather than just one.
  // [For use with "require" method]
  RequireAll bool
}
```

### Struct: Repo selector

RepoSelector has a number of defining features, including the ability to introduce complex targeting using the Exclude option.

```go
// RepoSelector targets repos
type RepoSelector struct {
  // Name is the repo name in glob format
  Name string

  // Language is a set of programming languages.
  // See the section about language detection below.
  Language []string

  // Exclude is a set of RepoSelectors targeting repos that should
  // not be matched by this selector.
  Exclude []*RepoSelector
}
```

### Struct: Action selector

```go
// ActionSelector targets Actions
type ActionSelector struct {
  // Name is the Action name in glob format
  Name string

  // Version is a semver condition or commit ref
  // Default "" targets any version
  Version string
}
```

### Detecting languages in repos

The GitHub API provides an endpoint, [List Repository Languages](https://docs.github.com/en/rest/repos/repos#list-repository-languages) [[Godoc](https://pkg.go.dev/github.com/google/go-github/v45/github#RepositoriesService.ListLanguages)], which lists the languages used in a repository.

See [linguist/languages.yml](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) for languages, where the key is the language name.

```js
// languages for ossf/allstar
{
  "Go": 283950,
  "Shell": 128
}
```

This endpoint returns the number of bytes written in each language. The policy should consider a repo to contain a language for the purpose of RepoSelector matching if either:
- the language is the repo's top language
- the repo has at least one language with more than 3000 bytes of code and this is one of them

### Determining whether an Action is "passing"

Because Actions run as part of workflows, we can determine if they are passing based on whether they are contained within a workflow which is passing in the latest commit. A workflow should be defined as passing if its status is not a pending status ("in_progress", "queued", "waiting", "requested") and its conclusion is "success".

While it isn't perfect at checking whether an Action is passing, this is the best way to do it because determining whether a particular job / step is failing requires more API requests and some guessing. (We would have to use [List jobs for a workflow run attempt](https://docs.github.com/en/rest/actions/workflow-jobs#list-jobs-for-a-workflow-run-attempt) for each relevant workflow run)

Relevant GitHub APIs for this are the following:

[List workflow runs by filename](https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs) [[Godoc](https://pkg.go.dev/github.com/google/go-github/v45/github#ActionsService.ListWorkflowRunsByFileName)]

[List commits](https://docs.github.com/en/rest/commits/commits#list-commits) [[Godoc](https://pkg.go.dev/github.com/google/go-github/v45/github#PullRequestsService.ListCommits)]

[Get repository content](https://docs.github.com/en/rest/repos/contents#get-repository-content) [[Godoc](https://pkg.go.dev/github.com/google/go-github/v45/github#RepositoriesService.GetContents)]
=> This can be used to list workflow files in a repo's `.github/workflows` directory.

### Checking Action versions and caching globs

Action versions will be checked using compiled [Masterminds/semver](https://github.com/Masterminds/semver) Constraints.

These, as well as compiled globs identified in the config, should be cached for at least each repo (for the scope of the Check function). While preferably they would be cached per-org, this isn't possible currently because new OrgConfig and RepoConfig structs are to be created for each call to the Check function.

If an Action is identified by a commit ref rather than a commit hash, a lookup should be performed to figure out which tag (often in semver format) it corresponds to for this version check.

The following endpoint can be used to correspond tags and commit hashes for a repo containing an Action:

[List tags for a repo](https://docs.github.com/en/rest/repos/repos#list-repository-tags) [[Godoc](https://pkg.go.dev/github.com/google/go-github/v45/github#RepositoriesService.ListTags)]

### Generating descriptions of rule failures

There are two different kinds of failures which will need to be generated. One is the case where an Action is denied by a deny rule and the other is where a require rule is not satisfied.

This is an example of the first type (deny):

```
Action helpful/require-go-sum version 1.0.3 hit deny rule "Deny default" (in rule group "Go repos"):
-> does not meet version requirement ">= 2.0.2" for require rule "Require Action confirming go.mod implies go.sum on all Go repos"
-> is not listed in require rule "Require a passing DAST Action for all repos"
-> is not listed in allow rule "Allow trusted Actions"
-> denied by deny rule "Deny default"
```

For the first type, the Action which was denied is listed along with the name of the deny rule and all allow / require rules it didn't match before being denied.

And this is an example of the second type (require):

```
Require rule "Require a passing DAST Action for all repos" (in rule group "All repos") not satisfied:
-> 0 / 1 requisites met
-> To resolve, do 1 of the following:
     - Add "stackhawk/hawkscan-action" with version satisfying ">= 2.0.0"
     - Fix failing Action "projectdiscovery/nuclei-action@main"
```

The explain feature for require rule evaluation is complex because it should understand specifically why an Action didn't qualify, including the case that it was present but didn't pass on latest commit when it was required to do so (according to the rule's mustPass option).

### Order and means of Rule evaluation
Rules are evaluated in an order based on their priority and type. They are effectively sorted by primarily priority and secondarily type, where require and allow are first and deny is last.

Deny rules are evaluated Action-wise. For each Action listed, the sorted rules which apply to the current repo are executed in order. If an allow or require rule applies to the Action before it hits a deny rule, or there is no deny rule, the Action is allowed. Otherwise, it is denied.

Require rules are evaluated Rule-wise. Each require rule is evaluated against the set of Actions present. Actions are only qualified for require rules if they are present in Workflows with at least the on fields "push" and "pull_request".

Allow rules are not executed independently and are only used during the evaluation of deny rules.

### Alternative 1: Require, Allow, and Deny Configuration Sections

This configuration arrangement puts rule methods front-and-center, with a require section and either an allow or deny section depending on whether an allowlist or denylist strategy is preferred.

```yaml
allow:
  - repo:
      name: "*"
    actions:
      - name: "actions/checkout"
require:
  - repo:
      name: "*"
    actions:
      - name: "stackhawk/hawkscan-action"
      - name: "projectdiscovery/nuclei-action"
```

### Alternative 2: List of Rules without RuleGroup

Alternative 2 consists of an org-level list of Rules, each of which contains a RepoSelector as well as the standard Rule fields mentioned in the proposed Rule struct.

This method is easy to understand for users, but leads to confusion about which rules apply to which repos, because RepoSelectors might accidentally not be kept consistent across rules expected to apply to the same repos.

For example, if an org uses a allowlist rule strategy but decides to exempt a repo from the strategy, it might just exempt the repo from the deny rule using RepoSelector Except, forgetting that the allow rules still apply to that repo.

![Action Policy Alternative 2 drawio](https://user-images.githubusercontent.com/14060354/183734844-4fab5c15-92a4-4c16-8e5a-f7e688823f5f.png)

#### Comparing proposed solution to alternatives

|  | Proposed solution | Alternative 1: Require, Allow, Deny Sections | Alternative 2: Rule list without RuleGroup |
|---|---|---|---|
| Flexibility of configuration | Configuration is highly flexible with ability to interweave allow, deny, and require policies (allowing the creation of denylist strategy for only a subset of repos, for example) | Configuration is less flexible because allowlist / denylist strategy applies to all repos | Same flexibility as proposed solution |
| Ease of configuration for users | Somewhat more complex due to verbose config, but less room for mistakes than Alternative 2 | Simple-to-write config | Slightly more difficult due to verbose config |
| Understandability of configuration for users | Rule priority is easy enough to understand because rules are labeled with their priorities. RuleGroups help manage evolving RepoSelectors | Somewhat straightforward interpretation of rule priority, but potential for desync between them as RepoSelectors evolve | Configuration is straightforward to understand because rules are ordered by priority, however there is potential for desync, like with Alternative 1 |

### Abuse

Because users can define rules of various complexity and they can involve compilation of many globs, some of the following restrictions could be applied eventually if needed:

- Number of rules
- Number of nested RepoSelectors (under Exclude)
- Number of total RepoSelectors
- Number of workflows

### Execution Details

This project should take about 2-4 weeks post-approval to complete.

Structs will be created in the config package, where users usually expect config structs to live, and notes similar to those about other policies will be added to the README.

The feature must be implemented and merged, then deployed to the primary OpenSSF Allstar instance.

Post-launch, rules can be designed on a per-organization basis, according to organizational needs.

Create tests for the Check function or some intermediary function(s) built to be testable. Consider creating tests for each struct's supporting functions.

# Proposal history

## 15 Aug 2022 Revisions: Priority

In response to discussion at the biweekly last week, the following changes were made to the proposal:

- Added priority to Rule to allow deterministic run order, regardless of order of rules in config
    - Priority is a string, one of "critical", "high", "medium", or "low"

Additional changes:
- Updated abuse section to be more specific about how to implement restrictions in the future

**Comment by ghost** [comment]
@josephperrott @hixie @godofredoc Would appreciate feedback on this proposal! Does this policy seem like it could help support the security goals of your teams by letting you manage Action use? Is there anything that might be missing?

Thanks!

**Comment by Hixie** [comment]
This is far enough outside my area of expertise that I don't feel qualified to really state an opinion. I'll defer to @godofredoc.

**Comment by godofredoc** [comment]
@drewroengoogle @sealesj please take a look.

**Comment by godofredoc** [comment]
#### Configuration file comments

* Should the `method: require` be moved to the actions level? This way we can target the specific action that must pass.
* If `method` is moved to the `actions` level then count becomes redundant.
* Should versions only allow commit hashes? it is recommended to use only pinned versions by hash(.e.g. scorecards raises alerts for tags or semver versions).

#### Actions allowed

It is mentioned a couple of times but doesn't seem to be covered in the configurations. Is this expected?

If AllStar provides an actions allowed list how will it interact with the github org configuration to allow list certain actions? would it inspect the runs and validate against the config in AllStar?

**Comment by ghost** [comment]
> * Should the `method: require` be moved to the actions level? This way we can target the specific action that must pass.
> * If `method` is moved to the `actions` level then count becomes redundant.

This is an interesting idea and could help with config verbosity. I don't think it works, though, in the case that someone setting the policy configuration wants to require some number of Actions within a set.

> Should versions only allow commit hashes? it is recommended to use only pinned versions by hash(.e.g. scorecards raises alerts for tags or semver versions).

Nice idea! While it would make sense for security, I'm not sure every team is interested in putting in the footwork to convert their Action refs to hashes. Maybe requiring Action commit hash should be an org-level option, disabled by default?

> If AllStar provides an actions allowed list how will it interact with the github org configuration to allow list certain actions? would it inspect the runs and validate against the config in AllStar?

I think it could be nice to have a feature which would let configurations inherit rules from other configs. This way it would be clear what's going on on the user's end if they decide to inherit suggested rules. The way it stands, Allstar will just look in the workflow files to see if the Actions are present and inspect workflow runs when Actions are expected to pass.

I appreciate the suggestions, Godofredo!

**Comment by azeemshaikh38** [comment]
The proposal looks awesome, thanks for writing it up @ethanent. Some comments:

- We should support this feature on a per-repository basis too. Having the `RepoSelector` embedded within `Rule` makes it counter-intuitive to apply these rules on a repository and also goes against the convention of existing AllStar policies. Would suggest moving the `RepoSelector` struct out of `Rule`. Maybe something like this:

```
type OrgConfig struct {
	OptConfig config.OrgOptConfig

	Action string

	RepoRules []RepoRule
}

type RepoConfig struct {
	OptConfig config.RepoOptConfig

	Action string

	Rules []Rule
}

type RepoRule struct {
        // If true, apply rule to all repos and use the `Repos` field to provide exceptions to the rule.
        Exception bool

        // A string input of __ALL__ applies across all repos.
        Repos []string

        //
        Rule Rule
}

type Rule struct {
        // Can be one of - REQUIRE | ALLOW | DENY | REQUIRE_ATLEAST
        Method string 

        // Only valid if `Method` is REQUIRE or REQUIRE_ATLEAST
        MustPass bool

        // Only valid if `Method` is REQUIRE_ATLEAST
        Min int

        Actions []ActionSelector
}
```

- Is there a usecase of specifying "minimum set of actions"? I can see why requiring atleast one of given actions is useful. Maybe consider doing away with the `Min` field altogether?
- IMO, we gain little by letting users target repos by language since we are already providing them a way to target by name. It adds extra complexity to the design for little advantage. 
- For checking the pass status of an action, could also consider using this API - https://docs.github.com/en/rest/checks/runs#list-check-runs-for-a-git-reference

**Comment by jeffmendoza** [comment]
Agree that the relationship between rules and repo-selectors is the most tricky. Which way is more likely to be one-to-many? Which is more verbose in config in that we wish to avoid config duplication, etc.

Also, consider that the standard config.OrgOptConfig isn't sufficient for repo selection, and it isn't a requirement for all Allstar policies. Therefore evaluate excluding it from the config entirely. 

Also, clarify for the language selection: for a repo-selector to apply to a repo, does the repo have to have any number of that language, or the language must be the most prevalent for that repo, or just above some threshold?

**Comment by josephperrott** [comment]
A couple topics I want to bring up after looking through this:

### Semver enforcement on actions
While using semver is valuable, because the version being checked is simply a mutable tag requiring certain semver does not provide a ton of certainty for an automated system.  The certainty still is coming from trust in the action author.  I don't know if that means that this should only allow commit sha based rules, like that it needs to come from any commit that has a specific commit as an ancestor.


### Permissions
An aspect of security that I think would be good to increase enforcement/tracking around is the permissions that are allowed for workflows.

I believe that allowing for enforcement of things like not allowing `contents: write` permissions except for certain actions, or requiring that all access is defined directly, rather than using something like `permissions: write-all`.
