### ISSUE TITLE
enforceOnAdmins, requireSignedCommits are not being applied

### ISSUE THREAD

**Issue by testworksau** [ossf/allstar#254]
Thanks for your work on this promising tool!

We've set up allstar with a global / org-wide `branch_protection.yaml` configuration in the `.allstar` repo. Almost all of the settings have been applied, except for the following:

```
# Admins should be subject to the same policies
enforceOnAdmins: true

# All commits must be signed
requireSignedCommits: true
```

Please see attached screenshot for details.

<img width="2537" alt="image" src="https://user-images.githubusercontent.com/11973031/184559511-4ea94171-a663-4d58-855d-acd48743b5f7.png">

**Comment by jeffmendoza** [comment]
Thanks for the report! I'll look into the code and test this out to debug.

**Comment by jeffmendoza** [comment]
@testworksau looks like it had been a while since I had actually deployed staging -> prod, and I didn't have the latest fixes for this area deployed. I went ahead and did that this morning. It should apply in 24-48 hours, let us know if it doesn't. Thanks!

**Comment by testworksau** [comment]
Hi @jeffmendoza - I can confirm this issue is now resolved 🎉
