### ISSUE TITLE
Organization repo name and config... match probot?

### ISSUE THREAD

**Issue by jpoehnelt** [ossf/allstar#27]
> create a repository named .allstar in your organization

Many GitHub apps are based on Probot and default to the .github repository for organization config. The default setting of this app requires splitting config into yet another repository.

At a minimum it would be nice if this app allowed specifying the org config location.

It would be nice to mirror https://probot.github.io/docs/best-practices/#configuration.

**Comment by jeffmendoza** [comment]
I would be worried about name collisions. I believe GitHub itself sort of "owns" the namespace of that repo, same with `.github` directory in repos. ex: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

Being able to configure it sounds great. A bit of a chicken and egg problem, where do you configure the configuration location. Happy to hear any proposals.

**Comment by jpoehnelt** [comment]
> I believe GitHub itself sort of "owns" the namespace of that repo

That really isn't the case and many apps follow the probot pattern. https://probot.github.io/docs/best-practices/#configuration

>Any configuration should be stored in the target repository. **Unless the app is using files from an established convention, the configuration should be stored in the .github directory**. See the API docs for context.config.

> context.config supports sharing configs between repositories. If configuration for your app is not available in the target repository, it will be **loaded from the .github directory of the target organization's .github repository**.

> User's can also choose their own shared location. Use the `_extends` option in the configuration file to extend settings from another repository.

**Comment by jeffmendoza** [comment]
Even if a popular bot framework uses the repo by default, it doesn't change whether GitHub considers it their namespace or not. We can assume that GitHub wouldn't do anything to break a large swath of apps. We can guess that an `allstar` directory in that repo would be safe from collisions, but I'd rather not assume or guess.

That said, supporting config it `.github` should be doable. I was thinking we don't even need to have a "config location config" but just a priority order. Look for `.allstar` first, if it doesn't exist then `.github/allstar` second.
