### ISSUE TITLE
[Feature Request] Check for presence of CODEOWNERS file

### ISSUE THREAD

**Issue by emtunc** [ossf/allstar#284]
Branch Protection is a good first step towards ensuring code is approved by _a_ member of the organisation. If we are to take this to the next level then we should be checking for a _valid_ CODEOWNERS file (presence of the file is sufficient to begin with).

I would like to see an issue raised when a CODEOWNERS file is missing in the root of a repository.

It's not a check that could have the "fix" action applied to it but that should be okay.

This could possibly sit under the _branch_protection.yaml_ config as you would typically only use CODEOWNERS as part of a Branch Protection stategy.

**Comment by Gby56** [comment]
@jeffmendoza this can be closed
