### ISSUE TITLE
Issues created by allstar-app could be improved

### ISSUE THREAD

**Issue by slonka** [ossf/allstar#29]
I think that it's crucial to include some actionable information when creating an issue of any kind. This is a follow up from this issue: https://github.com/envoyproxy/java-control-plane/issues/173. 

I think that a well created ticket should at least include the following information:

1. Why is this ticked created?
2. Why is the current situation bad?
3. What are the risks?
4. How can it be fixed? (step by step guide)
5. How to know it's fixed.

Let's look at the message in the linked issue:

```
Security Policy Outside Collaborators is out of compliance, status:
Found 1 outside collaborators with admin access.
```

In my opinion it does not inform why it's an issue and how to resolve it. A better message would be:

```
Security Policy "Outside Collaborators" is out of compliance.

This policy requires all users with admin access to be members of the organisation. That way if an account is compromised it can be quickly denied access to all resources of the organisation. To fix this you should:
1. Remove the user from the repository based access by going to settings -> permissions -> ...
2. Add the user to the organisation by going to -> ...

If you don't see the settings tab you probably don't have administrative access. Reach out to the administrators of the organisation to fix this issue.

This issue will auto resolve when the policy is in compliance.

If you have any questions - please reach out to XYZ.
```

If you have any questions or you'd like to agree/disagree please comment below. Also, I'm creating this issue in good faith, I really think better issue contents will improve this project.

Best regards,
slonka

**Comment by inferno-chromium** [comment]
Thank you, we will try to improve this bug filing templates based on your feedback!

**Comment by jeffmendoza** [comment]
Updated in #49 and #132, however improving clarity will be an ongoing quest.
