### ISSUE TITLE
Permissions for Github App seem too permissive for the current functionality

### ISSUE THREAD

**Issue by testworksau** [ossf/allstar#295]
When self-hosting the Allstar app, it seems the permissions required / listed [here](https://github.com/ossf/allstar/blob/main/operator.md#create-a-github-app) are a little too permissive.

I'm not sure why it needs read-only access to Environments, Deployments, Pages, Projects, Discussions, Commit Statuses, Secret scanning alerts (not that we have this option) or Webhooks as an example.

**Comment by jeffmendoza** [comment]
Yes, on the read side, I was liberal to future-proof against any new policies that could be added.
