### ISSUE TITLE
Enforce certain status checks in branch protections

### ISSUE THREAD

**Issue by artis3n** [ossf/allstar#30]
Accept an optional yaml list of status check names for the branch protection policy to enforce repos have enabled an organization's expected checks. The yaml list should accept objects containing at least the fields `name` and `required` (to enforce whether a particular status check should be marked as required).

I'm happy to take on this pull request myself if the maintainers approve of the issue.

**Comment by artis3n** [comment]
Maybe also, in the object: an optional `msg` field that overwrites the message given to developers if that status check is found missing. If not present a general "missing X status check" message will be outputted.

**Comment by jeffmendoza** [comment]
This sounds great. It would be good to propose the additional names and types of the members in [the config](https://pkg.go.dev/github.com/ossf/allstar@v0.0.0-20210812151424-aa093e731e2a/pkg/policies/branch#OrgConfig).

Why would `required` be needed. Why would you list a name of expected check, but it not be required?

The [GitHub data](https://pkg.go.dev/github.com/google/go-github/v38/github#RequiredStatusChecks) looks straight forward, just a list of strings.

**Comment by artis3n** [comment]
> Why would `required` be needed. Why would you list a name of expected check, but it not be required?

We have a bunch of status checks we supply through GitHub Apps in our org to give feedback to folks as they work on PRs, but they don't necessarily need to succeed before code is merged. e.g. providing teams early security feedback but the violations only _have_ to be fixed later on, teams can still merge code with the failed status check.

I'm fine with putting this together without the `required` field but that's my use case.

**Comment by artis3n** [comment]
Given the GitHub data it seems the status checks submitted must be considered required, which makes sense. So the new data going into the config would look like:

```yaml
status_checks:
  - mycheck
  - theothercheck
  - other
```

With no other metadata needed. Just the names

**Comment by jeffmendoza** [comment]
Sounds great, lgtm

**Comment by yorinasub17** [comment]
I had a need for this for our org's use case so I went ahead and took a stab at an implementation! https://github.com/ossf/allstar/pull/147

**Comment by azeemshaikh38** [comment]
FYI, Scorecard `Branch-Protection` data already has the status checks. Not needed right now, but can consider pulling in this info from Scorecard directly at some point.

**Comment by yorinasub17** [comment]
FYI #147 was just merged. Note that the final version changed the interface slightly to allow for specifying the GH app that should provide the context:

```yaml
requireStatusChecks:
  - context: "Analyze (go)"
    appID: 15368
  - context: "lint"
  - context: "build"
    appID: 15368
```

Refer to https://github.com/ossf/allstar/pull/147#discussion_r832761480 for rationale

**Comment by jeffmendoza** [comment]
Closed with above
