### ISSUE TITLE
False positive: branch protection rule violation on transferred repository

### ISSUE THREAD

**Issue by woodruffw** [ossf/allstar#303]
Hi there! Thanks for maintaining this tool.

We're currently using Allstar on [sigstore/gh-action-sigstore-python](https://github.com/sigstore/gh-action-sigstore-python), which was recently transferred from another org.

After we transferred the repository to the Sigstore org, we received an automated issue warning us of a stale review policy violation: https://github.com/sigstore/gh-action-sigstore-python/issues/32

Based on the current branch protection rules for `main`, this looks like a false positive. I've screencapped them below, for reference:

![image](https://user-images.githubusercontent.com/3059210/193671588-29b28549-ede3-4eda-a571-6872a85e0f61.png)

Please let me know if there's information I can provide!

**Comment by jeffmendoza** [comment]
Hi, thanks for reporting! I'll take a look at the logs and get back to you.

**Comment by woodruffw** [comment]
Thanks for the response @jeffmendoza! It turns out this was probably a misunderstanding on my part -- my colleague updated the setting *after* Allstar reported the violation, which I then saw and assumed wasn't detected correctly.

I'm closing this for now; will reopen if we see an actual false positive 🙂

**Comment by jeffmendoza** [comment]
Yes, Allstar is working a bit too slow now, We'd like to improve the responsiveness. Thanks for reaching out.
