### ISSUE TITLE
[Feature Request] Require review from Code Owners

### ISSUE THREAD

**Issue by testworksau** [ossf/allstar#312]
It would be great if this tool could handle the setting of the Require Code Owner Reviews sub-property of branch protections. 

This is governed by the `require_code_owner_reviews` property in the `required_pull_request_reviews` object.

This might go hand in hand with https://github.com/ossf/allstar/issues/284 (or negate the need for it).

https://docs.github.com/en/rest/branches/branch-protection#update-branch-protection

We are happy to contribute if you're happy to see this added.

**Comment by jeffmendoza** [comment]
Same as the other issue, happy to have more coverage of the BP options.

**Comment by coheigea** [comment]
It can be closed I think @jeffmendoza  ?
