### ISSUE TITLE
Add optOutForkedRepos

### ISSUE THREAD

**Issue by coheigea** [ossf/allstar#318]
I think it would be useful to have a "optOutForkedRepos" configuration option. For example, adding a SECURITY.md for forked public repos might not be desired.

If you approve I'll think about contributing a PR for it.

**Comment by jeffmendoza** [comment]
Yes, this would be great! Looks like the fork field is filled out on repo-get.
https://pkg.go.dev/github.com/google/go-github/v48/github#Repository.GetFork

**Comment by jeffmendoza** [comment]
Fixed with #342
