### ISSUE TITLE
New to Allstar

### ISSUE THREAD

**Issue by bhuvi11** [ossf/allstar#33]
Hello Team,

I am new to allstar and tried to use it in my GitHub repository. I have few questions
1) Is it specific only to the GitHub repo? Does it have a docker image or CLI to use it in local/ other git remote repositories

2) I have configured .allstar folder wiht the specified 4 policy yaml file. I dont see any issue or any process running to indicate a check is running and i need to wait for the result. Where can i see the result?

3) Does allstar use scorecard internally?

Thanks in advance.

**Comment by bhuvi11** [comment]
Hello Team,

I have installed the app and given access to all my repositories.
I do have security issues. I am not sure why Allstar is not able to detect and create issues.
Eg, i dont have SECURITY.md file. Allstar should have created an issue similar to : 

> https://github.com/envoyproxy/java-control-plane/issues/174

Is there something else I need to configure?
This is my public repo for reference : 
> https://github.com/bhuvi11/test_allstar

Please help

Thanks in advance

**Comment by bhuvi11** [comment]
Hello Team,

In addition to the above issues, i am trying to do the below operation
1) Clone the allstar repo
2) Create a new github app
        Fetch the app ID
        Get the .pem file
3) go build /cmd/allstar

I see allstar is built, now how to use it ?
Can i use it in local desktop?

Note: Using windows

Please help

Thanks in advance

**Comment by bhuvi11** [comment]
@jeffmendoza : Can you please help me with the queries? 
Am i missing anything in the configuration?

**Comment by jeffmendoza** [comment]
Hi @bhuvi11 I have a bug, where the Allstar run is failing on private repos that have the branch protection policy enabled. GitHub doesn't support branch protection on private repos unless you upgrade. Right now any of your repos after "f" alphabetically are not being checked, as there is a repo causing the error there. I'll have this fixed shortly.

**Comment by bhuvi11** [comment]
Hello @jeffmendoza,
Thanks for your reply.

- Is there an item in your roadmap that provides allstar as a CLI or a docker image? I am curious to add allstar as an integration. I believe the GitHub app will limit us from doing it .

- I would also like it to be scanning git repositories, not just GitHub, is that in your roadmap
 
- I am as well trying to use it for enterprise versions and for private repositories. Please help me understand that as well.

Please guide me on how I can use allstar

Thanks in advance.

**Comment by jeffmendoza** [comment]
> Is there an item in your roadmap that provides allstar as a CLI or a docker image? I am curious to add allstar as an integration. I believe the GitHub app will limit us from doing it .

Not currently. Policies are based on GitHub APIs (ex: branch protection). Enforcement actions are GitHub issues at the moment.

> I would also like it to be scanning git repositories, not just GitHub, is that in your roadmap

No, see above.

Take a look at scorecards https://github.com/ossf/scorecard/ to run on individual repos.

> I am as well trying to use it for enterprise versions and for private repositories. Please help me understand that as well.

This should work, not all policies will be applicable for private repos (ex: SECURITY.md).

**Comment by bhuvi11** [comment]
Hello @jeffmendoza ,
Thanks for the explanation.

Is the above mentioned issue resolved?

> Hi @bhuvi11 I have a bug, where the Allstar run is failing on private repos that have the branch protection policy enabled. GitHub doesn't support branch protection on private repos unless you upgrade. Right now any of your repos after "f" alphabetically are not being checked, as there is a repo causing the error there. I'll have this fixed shortly.

**Comment by jeffmendoza** [comment]
Sorry for not being specific. I opened #37 to cover the issue. Not fixed yet.
