### ISSUE TITLE
New package release?

### ISSUE THREAD

**Issue by ArisBee** [ossf/allstar#346]
Hello,

I see the latest release (`v2.0`) is almost 1 year old. There has been some new interesting checks such as scorecard support that have been added to the repository since then.

Would it make sense to create a new release including latest changes?

Best,

**Comment by jeffmendoza** [comment]
Yes, @coheigea has added a few new features recently. I'll get those all in then do a release soon.

Past folks I've talked to were just building from head, but I'd like to be able to provide an updated container image regularly. Just need to keep on top of it.

**Comment by jeffmendoza** [comment]
https://github.com/ossf/allstar/releases/tag/v3.0
