### ISSUE TITLE
Allstar frequency

### ISSUE THREAD

**Issue by bhuvi11** [ossf/allstar#35]
Hello Team,

I am curious to understand the frequency in which allstar scans the repositories to identify security policy violations?

I believe allstar doesn't use webhooks, so how will it know if a push or any action that happens in the GitHub repository?

Thanks in advance

**Comment by jeffmendoza** [comment]
It's essentially continuously polling. Which can be seen here: https://github.com/ossf/allstar/blob/main/pkg/enforce/enforce.go#L120
Single threaded, looks like a full poll of all repos is around 20 min at the moment, as more people have installed the app.

We plan to move to a webhook model as the install base grows to save cycles and improve responsiveness.

**Comment by bhuvi11** [comment]
Hello @jeffmendoza,

Thanks a lot for the explanation
