### ISSUE TITLE
Feature: Publish allstar image

### ISSUE THREAD

**Issue by raghavkaul** [ossf/allstar#372]
What's the best current public available container image to pull? I see:
- gcr.io/allstar-ossf
- ghcr.io/ossf/allstar

Neither of these appear to be publicly accessible.

**Comment by jeffmendoza** [comment]
Thanks for asking, as it's not clear.

The OpenSSF instance of Allstar uses `gcr.io/allstar-ossf` in it's CICD for deployment:
Published: https://github.com/ossf/allstar/blob/main/cloudbuild.yaml#L7
Deployed: https://github.com/ossf/allstar/blob/main/cloudbuild.yaml#L10
It wasn't my intention to have this be a public image.

The release process publishes and signs `ghcr.io/ossf/allstar` here: https://github.com/ossf/allstar/blob/main/.github/workflows/release.yaml#L23

The only ones published are:
ghcr.io/ossf/allstar:v2.0
ghcr.io/ossf/allstar:v3.0

These should be public, note there is no `latest` tag, as using latest is discouraged. LMK if you can't pull those tags.

If you have a usecase to use an image off head https://github.com/ossf/allstar/blob/main/.github/workflows/postmerge.yaml could be updated to publish to ghcr.io/ossf/allstar as well.

**Comment by azeemshaikh38** [comment]
Thanks @jeffmendoza. For context, we'd like to self-host AllStar by pulling the official public image released by ossf/allstar directly. Some questions:

-> Do you expect the public images to be released/maintained in the long-term? Since the official documentation on the repo does not expose a usecase for AllStar clients to be pulling the public image, want to make sure what we're trying is viable with the project's long-term plan.
-> I assume `ghcr.io/ossf/allstar:v3.0` is the latest production image?

**Comment by jeffmendoza** [comment]
> Do you expect the public images to be released/maintained in the long-term? 

Yes

> I assume ghcr.io/ossf/allstar:v3.0 is the latest production image?

Yes

Yes, we intend to continue to make regular releases ( https://github.com/ossf/allstar/releases ) and have those published container images be a recommended distribution method.

What hasn't been fully settled is the release cadence. It has been a little ad-hoc as the rate of feature development ebbs and flows.

**Comment by azeemshaikh38** [comment]
Makes sense, thanks.

**Comment by jeffmendoza** [comment]
Ah, I just saw there was an incident with packages this morning: https://www.githubstatus.com/incidents/ybnn77s3lyf8
@raghavkaul this may be why `ghcr.io/ossf/allstar` was unavailable for you then.

**Comment by raghavkaul** [comment]
Ah yeah, that was about the time I was pulling from ghcr.io. `ghcr.io/ossf/allstar` works now, thanks for the clarification! Closing now.
