### ISSUE TITLE
which file I need to edit to change the interval of "fix" action schedule?

### ISSUE THREAD

**Issue by sfc-gh-smisra** [ossf/allstar#386]

**Comment by sfc-gh-smisra** [comment]
I have installed my own instance

**Comment by jeffmendoza** [comment]
The enforce loop delay is here:
https://github.com/ossf/allstar/blob/main/cmd/allstar/main.go#L62

Every time a policy is checked, it will try to "fix" if that is the configured action.

I  could see this being a CLI option if needed.
