### ISSUE TITLE
Clarification on administration permissions of deployed app

### ISSUE THREAD

**Issue by netomi** [ossf/allstar#390]
Hi,

when trying to install the deployed app https://github.com/apps/allstar-app the following permissions are required:

* Read access to Dependabot alerts, actions, code, commit statuses, deployments, discussions, environments, metadata, packages, pages, pull requests, repository hooks, repository projects, secret scanning alerts, and security events
* Read and write access to administration, checks, and issues 

The write access to administration is scary and not clear why it is needed.

However, when looking at the operator instructions at https://github.com/ossf/allstar/blob/main/operator.md#create-a-github-app, the permissions for administration are required to be read-only.

Can you clarify on this discrepancy? We would ofc prefer to install the app w/o write access to administration.

**Comment by netomi** [comment]
Looking at the code for admin policies, the relevant fix method is not implemented yet:

https://github.com/ossf/allstar/blob/main/pkg/policies/admin/admin.go#L432

So I wonder if this permission is needed at all or should be made at least optional.

**Comment by jeffmendoza** [comment]
The Admin-write permission is needed for the "fix"action on Branch Protection. Unfortunately GitHub does not allow optional permissions for Apps. We have thought of running two App instances.

**Comment by jeffmendoza** [comment]
The operator.md doc is out of date and needs to be updated with the new requirement, and a new screenshot.

**Comment by netomi** [comment]
Ty for the quick clarification.
