### ISSUE TITLE
Regression is causing app deletion

### ISSUE THREAD

**Issue by coheigea** [ossf/allstar#393]
Hi @jeffmendoza @raghavkaul ,

The recent PR merged https://github.com/ossf/allstar/pull/387 has a bug which is causing the GitHub app to be deleted unless the "GITHUB_ALLOWED_ORGS" environment variable is defined. It caused our scans to fail due to the mysterious deletion of the GitHub app, which we have now fixed by setting the environment variable :-)

This seems contrary to the note on the PR which says that "if the operator hasn't configured an Allowlist, we fail open."

**Comment by raghavkaul** [comment]
Ah, I think I see the bug. I'll submit a PR and additional tests shortly.

**Comment by jeffmendoza** [comment]
Oh no! So sorry! Yes, as you see this is a bug and not the intention. I just checked our staging instance now and it has uninstalled itself as well.

Thanks for reporting! Especially before I deployed to the prod public instance.

**Comment by coheigea** [comment]
No worries, glad to help in catching the issue before it's released! :-)
