### ISSUE TITLE
Provided a hosted Allstar with reduced administrator permissions

### ISSUE THREAD

**Issue by tellison** [ossf/allstar#396]
As mentioned [here](https://github.com/ossf/allstar/issues/390#issuecomment-1490503697), the hosted Allstar app requires elevated Admin permissions to support the 'fix' action. Granting this level of access to many organisations is unacceptable, and limits adoption of the tool.

This issue to request running a second install of the App with read-only Administrator permissions so that issue and log action can be used.

**Comment by jeffmendoza** [comment]
Agree that this is an option that we want as a project. I'd be looking for another maintainer to help on the operations side. (https://github.com/ossf/allstar/blob/main/contributor-ladder.md). 

Also, it seems like most folks with anything sensitive are opting to run their own Allstar instance. I'm not sure how many would want to use a public instance with the reduced functionality (can't fix branch protection).

**Comment by tellison** [comment]
Understood. Running an instance is not going to be acceptable for the Eclipse Foundation. Sorry that it didn't work out.
