### ISSUE TITLE
Can I pause or change how often the allstar-app bot posts comments if an issue is open

### ISSUE THREAD

**Issue by shenxianpeng** [ossf/allstar#406]
The allstar-app bot keeps posting comments every day or two if the created issue has not been closed.
Can I pause or change how often the allstar-app bot posts comments? 

More details could be found bellow

- Example issue: https://github.com/PlaywithX/play-with-allstar/issues/1
- configuration file: [branch_protection.yaml](https://github.com/PlaywithX/.allstar/blob/main/branch_protection.yaml)

**Comment by jeffmendoza** [comment]
It is currently only configurable at the operator level: https://github.com/ossf/allstar/blob/main/pkg/config/operator/operator.go#L92-L96 but not configurable for users of the public instance.

We have a feature request issue open, and would welcome a PR for this: https://github.com/ossf/allstar/issues/117
