### ISSUE TITLE
Publish JSON schemas to validate configurations

### ISSUE THREAD

**Issue by yu-iskw** [ossf/allstar#407]
## Motivation
As a lot of code editors enable us to validate files with JSON schemas, it would be great to publish JSON schemas of the allstar configurations. We can also publish them to https://json-schema.org/ .

**Comment by jeffmendoza** [comment]
The configs are defined as go structs: https://github.com/ossf/allstar/blob/main/pkg/config/config.go#L33-L67

Do you know of any tools that can generate a schema from those?

**Comment by yu-iskw** [comment]
@jeffmendoza It seems that I found a couple of tools/packages to generate a OpenAPI JSON schema from golang types. But, I haven't looked into them whether or not they support JSON schema 7. 

- https://pkg.go.dev/github.com/getkin/kin-openapi/openapi3gen
- https://github.com/invopop/jsonschema

**Comment by yu-iskw** [comment]
@jeffmendoza We found another package looks nicer than what I shared before. 

- https://github.com/mcuadros/go-jsonschema-generator
- https://go.dev/play/p/eDn9U1s9ru4

**Comment by yu-iskw** [comment]
@jeffmendoza I did't find any tool to generate a JSON schema from the struct types, which follows the draft-7 specification of JSON schema. 

1. Generate the base JSON schema with go-jsonschema-generator
2. Ask ChatGPT to convert it to follow the draft-7 spec.
3. Manually remove something like required properties in the JSON schema

https://github.com/yu-iskw/allstar-jsonschema/blob/main/allstar-config.json

**Comment by yu-iskw** [comment]
I figured out there is no perfect existing tool to generate JSON schemas from the definitions in golang. After all, I took advantage of ChatGPT to generate the JSON schemas. 

https://github.com/yu-iskw/allstar-jsonschema
