### ISSUE TITLE
Own instance of allstar

### ISSUE THREAD

**Issue by bhuvi11** [ossf/allstar#41]
Hello @jeffmendoza,

I am trying to create an own instance of allstar.

- I cloned the repository
- build the cmd/allstar
- tried running it locally using the "allstar" command
Got the below error,
`{"severity":"CRITICAL","error":"open variable gcpsecretmanager://projects/allstar-ossf/secrets/allstar-private-key?decoder=bytes: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.","time":"2021-08-23T15:16:18+05:30","message":"Could not load app secret, shutting down"}`
Is it because allstar can not be run locally?

**Comment by jeffmendoza** [comment]
See operator.md and specifically [this section](https://github.com/ossf/allstar/blob/main/operator.md#get-id-and-key) fore setting up the private key after creating the github app. If you don't want to use CDK for storing the key secret, you could change the code to read the key from a local file.

I recommend changing the label strings in [operator.go](https://github.com/ossf/allstar/blob/main/pkg/config/operator/operator.go) to not conflict with the main allstar app instance.
