### ISSUE TITLE
Sign correct container when publishing releases

### ISSUE THREAD

**Issue by jeffmendoza** [ossf/allstar#417]
In the release workflow, we sign the container that is publicized for the release, which uses the version tag of the release:

https://github.com/ossf/allstar/blob/main/.github/workflows/release.yaml#L25

I was reading that it is not best practice to sign containers with mutable tags, and to only sign the digest tag.

**Comment by jeffmendoza** [comment]
cc @cpanato Is this correct? Thanks!

**Comment by cpanato** [comment]
yes, and I saw that and was planning to get that fixed.
Give me some time and I will send a PR to get that fixed :)
