### ISSUE TITLE
Not requiring approvals does not imply approval count of 0?

### ISSUE THREAD

**Issue by TobiX** [ossf/allstar#419]
Consider this either a question or a bug report 😄 

When setting
```
requireApproval: false
```
in `branch_protection.yaml`, one still gets the error
> PR Approvals below threshold 0 : 1 for branch main

if "Require a pull request before merging" is active and "Require approvals" is not active in a repository.

Question: Shouldn't `requireApproval: false` imply `approvalCount: 0`? And if not: Should this "surprising" (at least for me) behaviour be documented?

**Comment by jeffmendoza** [comment]
Yes, this makes sense. I think they are just being checked/reported independently, and `requireApproval` should gate the count.

**Comment by jamestran201** [comment]
@jeffmendoza I've opened a small [PR](https://github.com/ossf/allstar/pull/423) to address this, would appreciate a review when you have time, thanks!
