### ISSUE TITLE
Organization wide SECURITY.md file does not fulfill SECURITY.md policy

### ISSUE THREAD

**Issue by josephperrott** [ossf/allstar#43]
If an organization has an organization level `SECURITY.md` file defined as outline in [About default community health files](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file), I would expect that this would satisfy the SECURITY.md policy check.

Instead, an [issue](https://github.com/angular/dev-infra/issues/192) was created with a link to create this policy, but this link is actually just to our [policy](https://github.com/angular/dev-infra/security/policy) itself, which is defined [here](https://github.com/angular/.github/blob/master/SECURITY.md).

**Comment by jeffmendoza** [comment]
Thanks for pointing this out. It looks like setting the org-wide security policy does not make a phantom SECURITY.md "appear" in the repo, which is what this policy looks for. Looks like just the security tab is updated in the UI. We will have to find a way to detect this in the API, or if that does not exist, just re-implement GitHub's logic and check the org-level `.github` repo.

**Comment by josephperrott** [comment]
From a quick look it looks like using Github's v4 GraphQL API you can request this information directly.

The [Repository](https://docs.github.com/en/graphql/reference/objects#repository) object has an attribute `isSecurityPolicyEnabled`.  Personally, I don't have enough experience with go to just jump into this repo and try to make it happen.  But it seems to be pretty straight forward if you would like to leverage the Github GraphQL API.

**Comment by azeemshaikh38** [comment]
@jeffmendoza FWIW Scorecard already handles the case of scanning the `.gtihub` org repo for security policy file - https://github.com/ossf/scorecard/blob/main/checks/security_policy.go. Maybe consider calling the Scorecard SecurityPolicy check directly?

**Comment by jeffmendoza** [comment]
Some more details from #46
> github docs:
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

> Show SECURITY.md can be under root, docs, or .github

**Comment by jeffmendoza** [comment]
Fixed
