### ISSUE TITLE
Allow custom label on raised issue

### ISSUE THREAD

**Issue by jdhaines** [ossf/allstar#44]
Allstar always creates it's issue(s) with a gray label called `allstar`.  We use an organization-wide label associated with security / risk that we'd like it to use.  I've read through the code and config files and I don't see how to configure allstar to use a custom label, but it seems like something that would be possible based on the way the config works currently.

Thanks for the great tool!

**Comment by jeffmendoza** [comment]
Thanks for the suggestion, right now it is only configurable at the operator level. I agree it would be good to have this in the org config.

https://github.com/ossf/allstar/blob/main/pkg/config/operator/operator.go#L40

**Comment by jeffmendoza** [comment]
Fixed by #68
