### ISSUE TITLE
Allstar Integration on Enterprise version of GitHub

### ISSUE THREAD

**Issue by 1633605** [ossf/allstar#45]
Hello Team,

I have followed your documentation and enabled allstart github app as below.

1. Create .allstar repo under the org as internal (public is not allowed in our enterprise either private or internal)
2. Create all the four config files and opted for scanning all repositories

Do not see any issues being created automatically, Does it support GitHub enterprise with allstar as internal repository type?
Is there anything else to configure to get the issues created in respective repositories?

Thanks

**Comment by jdhaines** [comment]
We have the exact system you're describing working.  This may sound dumb, but did you actually install the GitHub app itself?  We were relatively new to GitHub and I set up the config but missed the step of actually installing the application.  Afterwards it seemed like a silly thing to miss, but it's worth the post in case you did the same thing.

**Comment by 1633605** [comment]
@jdhaines Thanks for the feedback. It worked when the configuration is defined as below.
Step1: 
![image](https://user-images.githubusercontent.com/86053062/132216666-f8795ae5-af5b-41c4-b16a-c2b41e4145d2.png)


I was trying to run it across the repos under organisation with below config(.allstar.yaml)
Step2: 
optConfig:
 optOutStrategy: true

but it  was not working as expected to create issues across the repos. 

I tried again with new repositories as mentioned in step#1, didn't seen any issues being created for new repos which are added today. Please advise if there is something to be modified.

**Comment by jdhaines** [comment]
One thing I notice is that the repo in the organization should be called `.allstar` but the file in that repo should be `allstar.yaml` with no leading period. This one is working for me in a `.allstar` repo in the organization. 

![Screenshot_20210906-084454-841.png](https://user-images.githubusercontent.com/3834260/132219808-bfcbdadb-d78b-4420-9cc6-a5ee302e7de0.png)

Also it's a `.yaml` file so the spacing / tabs is meaningful.

**Comment by 1633605** [comment]
@jdhaines Yes the repo is created as below screenshot.
![image](https://user-images.githubusercontent.com/86053062/132224733-bdad540a-293e-44f0-a855-28ecf91e2a78.png)
Here is the screenshot of repository level config.

![image](https://user-images.githubusercontent.com/86053062/132224815-fcef6c45-bed5-4ca8-a5c8-b0522acf3311.png)

All the four files below are created with same config.
1. branch_protection.yaml
![image](https://user-images.githubusercontent.com/86053062/132225503-7c5e25ec-2102-496a-bba1-01d88db8f448.png)

2. binary_artifacts.yaml (same as below screenshot)
3. outside.yaml (same as below screenshot)
4. security.yaml
![image](https://user-images.githubusercontent.com/86053062/132225094-4da66afa-67a0-4845-8d10-286d73302f41.png)



I see first rule and security rule creates issues intermittently, when i define the optOut Strategy. However creation of issues are not consistent across the repos for all the rules. 
For example in one of the repo only security.md related issue is created but the issue related to branch protection rule is not created.
Is it consistent and working in expected behaviour at your side?
Please advise for any corrections required.

**Comment by jeffmendoza** [comment]
@1633605-Phaneendra Which org? I can look at the logs for errors.
