### ISSUE TITLE
SECURITY.md not found under .github/ folder

### ISSUE THREAD

**Issue by aarne** [ossf/allstar#46]
**example issue:**

https://github.com/stackables/cloudevents-router-gcp/issues/3

Security Policy SECURITY.md is out of compliance, status:
SECURITY.md not found.
Go to https://github.com/stackables/cloudevents-router-gcp/security/policy to enable.

**github docs:**
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

Show SECURITY.md can be under root, docs, or .github

**Comment by jeffmendoza** [comment]
Thanks! Added info to #43
