### ISSUE TITLE
Allstar not opening issue on a fork

### ISSUE THREAD

**Issue by sakshi-1505** [ossf/allstar#480]
Hello Team;

I am working on getting Allstar evaluated for OpenTelemetry community; to test out things myself I tries configuring Allstar on my fork https://github.com/sakshi-1505/opentelemetry-go/tree/main/.allstar . I have given permission & have already installed the Allstar application just for the above repository, yet I don't see anything yet.

Apart from that; is there a way to check the status of runs/logs for Allstar if using ossf hosted version.

**Comment by jeffmendoza** [comment]
Hi, Allstar polls, and the public instance takes a while to get to each repo, normally around 24 hours or so. I see that some issues were eventually opened.

**Comment by sakshi-1505** [comment]
Thanks @jeffmendoza My issues were opened after 48hr. Looks fine for us rn ig
