### ISSUE TITLE
Prevent enforcement of `Branch Protection` on archived repositories

### ISSUE THREAD

**Issue by josephperrott** [ossf/allstar#489]
Currently if a repositories is checked for branch protection and is archived, it is seen as not having branch protection.

An archived repo cannot have any changes to any of the branches, which should be considered as fully locked down protection.

**Comment by jeffmendoza** [comment]
You could use the `optOutArchivedRepos: true` setting in `branch_protection.yaml` (ex: https://github.com/googleknowledge/.allstar/blob/main/binary_artifacts.yaml#L3)
https://pkg.go.dev/github.com/ossf/allstar@v0.0.0-20240301223750-24b20ace2adf/pkg/config#OrgOptConfig
