### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by pburkholder** [ossf/allstar#511]
We have an instance of Allstar running as a GitHub action that keeps crashing with 

```
Killed
Error: Process completed with exit code 137.
```

about 15 seconds after starting a Binary Scan. The internet tells me this may be an OOMKiller at work. It looks like you've made some commits to address memory usage, could you make a Release with your latest fixes? Thanks!

**Comment by pburkholder** [comment]
Correction - the apparent OOM killer kicks in about 15s after starting the scan

**Comment by jeffmendoza** [comment]
Hi @pburkholder Will Do!
Yes, #496 changes how memory is held and frees the memory after each run. Originally we thought the cache would be small enough to keep around, but that hasn't worked out on the public instance.
#497 changes the number of concurrent workers, and allows config by env var. More concurrent workers means more memory in use at each time.

I'll get a release out tomorrow (Friday).

**Comment by jeffmendoza** [comment]
That said, I'm still working through issues in the public instance, so there might be other problems with the binary scan. I'll keep debugging it.

**Comment by pburkholder** [comment]
Unless there's another newer new release coming, I'm going to close this. Thanks!
