### ISSUE TITLE
Document recent changes to the generic Scorecard policy

### ISSUE THREAD

**Issue by justaugustus** [ossf/allstar#537]
> So this will change the name needed for the `-policy` cli option to only run this policy. https://github.com/ossf/allstar/blob/main/cmd/allstar/main.go#L46-L62
>
> It will change the "area" value for all the structured logging in this policy.
>
> It will change the name of the policy in the structured summary results that allstar logs on each loop https://github.com/ossf/allstar/blob/main/pkg/enforce/enforce.go#L157-L160
>
> I think this is ok and is just something to call out in release notes.

_Originally posted by @jeffmendoza in https://github.com/ossf/allstar/pull/536#discussion_r1663223923_

**Comment by jeffmendoza** [comment]
Added notes to release: https://github.com/ossf/allstar/releases/tag/v4.2
