### ISSUE TITLE
Interested in support for self-hosted GHE installation

### ISSUE THREAD

**Issue by SebastianBezold** [ossf/allstar#552]
Hi Allstar Team,

We are currently evaluating the use of OSSF Allstar on our self-hosted Mercedes-Benz GitHub Enterprise instance.

Before we could get it to work, we had to modify all the locations where GitHub clients are created to configure them to use our internal URL, as there is currently no option to set this via configuration or parameter.

We believe that there may be more self-hosted GitHub Enterprise cases beyond our company, and we would like to know if you would be interested in enhancing OSSF Allstar to support this scenario.

If this is of interest to you, we would be happy to get in touch and contribute to the development of this feature.

**Comment by jeffmendoza** [comment]
Hello! Yes, this sounds like an excellent item to be configured. The current operator configuration is all under https://github.com/ossf/allstar/blob/main/pkg/config/operator/operator.go Usually there is a default and an env var that can override it. I'd like all future env vars to start with `ALLSTAR_`. 

Please let me know if there is anything I can answer to help out. I'm also in the #allstar channel in the OpenSSF slack. (https://openssf.org/getinvolved/)

**Comment by SebastianBezold** [comment]
Hi @jeffmendoza, 

great to hear! I'll see, that I'll provide a suggestion via PR the upcoming days. 
Thanks for your input on the desired implementation details!
