### ISSUE TITLE
Preview mode

### ISSUE THREAD

**Issue by Hixie** [ossf/allstar#58]
I administer an org with many, many repositories with varying levels of security (and varying levels of importance). I would love to enable allstar globally, but I am concerned that it will file hundreds of issues on various repos that may be secret, archived, unimportant, or some combination of the above, as well as filing issues that are known to be bogus (for example some of our repos are intentionally for storing binary files so the whole "don't store binary files" thing won't work in those repos).

What I would like is a way to get a preview of what allstar is going to complain about ahead of me doing something with public visibility.

**Comment by jeffmendoza** [comment]
Yes, I completely agree that this is a top issue to solve. Currently, I'm not sure of how it could work. We don't want to post the preview data publicly without some configuration action by the org-owner. A long-term solution could be a private portal that you log into with your GitHub credentials, and Allstar only shows you the results that you own. That would take some time to build.

A quicker hack that has come to me when thinking about this now is to create a single issue on the `.allstar` repo with the results of a preview. How does that sound to you? Any suggestions? Thanks!

**Comment by jeffmendoza** [comment]
Another thing: without preview mode a good way to slowly enable might be:

First use opt-in mode and explicitly list your important and active repos.

Next, after that goes well, switch to opt-out mode and opt-out a list of your old / stale repos that you wouldn't fix to avoid opening unnecessary issues on those. (Though I'd consider archiving those repos as well). With this config Allstar would be enabled on newly-created repos by default.

**Comment by Hixie** [comment]
A single issue in the .allstar repo would work great. That would also be a sufficient work-around for https://github.com/ossf/allstar/issues/59 for now.

**Comment by jeffmendoza** [comment]
Sounds good, I'll write up a proposal.

**Comment by Hixie** [comment]
One thing that would be valuable is if this preview did not report problems in archived repos. I mention this only because the logs you kindly provided me for flutter do include things like "this repo doesn't have branch protection" for repos that are actually archived and thus don't need branch protection (because they have the ultimate protection, heh).
