### ISSUE TITLE
Where will issues be submitted?

### ISSUE THREAD

**Issue by Hixie** [ossf/allstar#59]
For the flutter org, we have lots of repos but (with a few small exceptions) we use flutter/flutter/issues for all of them. Where will allstar try to submit issues if I enable that?

**Comment by jeffmendoza** [comment]
Issues are submitted on the repo for which the policy violation is found.

**Comment by Hixie** [comment]
Any chance we could have a configuration option to put issues into a different repo's issues database? Most of our repos have issues disabled so we wouldn't be able to get notifications in the current scheme.

**Comment by jeffmendoza** [comment]
Yes, this sounds great. Currently #56 is adding an "ActionConfig" section to the org config for github labels. A configurable repo makes sense there as well.

**Comment by jeffmendoza** [comment]
Custom label in #68, issues repo in #80
