### ISSUE TITLE
Documentation is confusing because of non-existent features being documented

### ISSUE THREAD

**Issue by Hixie** [ossf/allstar#60]
It would be significantly clearer if the documentation only included actual implemented features rather than being aspirational.

For example, "fix" is listed as a possible action, separate from the "Proposed, but not yet implemented actions", but later is revealed to do nothing yet. It would be better to just not list it until it does something.

**Comment by jeffmendoza** [comment]
Fix action is now in for some and not for others. Docs updated in #87
