### ISSUE TITLE
Make opt-in strategy more performant

### ISSUE THREAD

**Issue by jonhall54** [ossf/allstar#611]
Reviewing the DEBUG logs the `allstar.yaml` file from the repo `<my-org>/.allstar` is being read on each execution for each repo. However, in the opt in strategy, scorecard still attempts to run disabled checks in repos which are not opted in. While no output is provided, for large GitHub organisation this means the time to obtain and refresh results is very long.

**Proposal:**
- Review the `.allstar/allstar.yaml` as currently done.
- Only analyse the repos which are opted in.
- Once complete, re-read `.allstar/allstar.yaml` and continue.

**Benefits:**
- Time is not wasted analysing repos and impressing output.
- For large organisations with many repos, allow for performance tuning, as well as security output tuning.
- For private orgs, app's backend could be run as a CRON-type GitHub Action without wasting GHA minutes.
- Better performance from OpenSSF-hosted runners.

**Comment by jeffmendoza** [comment]
@jonhall54 Thanks for asking for help. Are you using the `DO_NOTHING_ON_OPT_OUT` option? More details here:

https://github.com/ossf/allstar/blob/3f9627a89e0c1305ec7c7748b573dc3cea17a248/pkg/config/operator/operator.go#L62-L69
https://github.com/ossf/allstar/blob/3f9627a89e0c1305ec7c7748b573dc3cea17a248/pkg/config/operator/operator.go#L134-L140

If not, try setting  `DO_NOTHING_ON_OPT_OUT=true` and see if that works for you. If you are setting that, then there is probably a bug in the Scorecard policy that I'll look into.

**Comment by jonhall54** [comment]
@jeffmendoza when running a `allstar.yaml` in the org-level .allstar repo with the following:
```
optConfig:
 disableRepoOverride: true
 optOutStrategy: false
 optInRepos:
 - .allstar
```

With the environment variable `DO_NOTHING_ON_OPT_OUT`, it simply opts out of all the repos, including those opted in. This is also the case when running `./allstar -once -repo <org name>/.allstar`.

**Comment by jeffmendoza** [comment]
Yes, after adding the `allstar.yaml` to enable the bot overall, next add individual yaml files to turn on the individual policies. ex: https://github.com/jeffmendoza/dot-allstar-quickstart/blob/main/binary_artifacts.yaml to turn on the Binary Artifacts policy. The links to the  policy config definitions are here: https://github.com/ossf/allstar?tab=readme-ov-file#policies

**Comment by jonhall54** [comment]
@jeffmendoza all makes sense, and it does work. My comment is more that the API calls for opted out repos appear to still be made. While GitHub Apps don't suffer that many rate limits for orgs with hundreds of repos the time to execute is quite long.

Skipping some checks for certain repos has resolve the issue and it at least finishes the org within a few hours.
