### ISSUE TITLE
It's unclear how "disableRepoOverride: true" in the allstar.yaml file interacts with policy files

### ISSUE THREAD

**Issue by Hixie** [ossf/allstar#63]
The readme (https://github.com/ossf/allstar) links to a sample config repository whose policy files contain "disableRepoOverride: true". It's not clear from the documentation whether this overrides, combines with, or is overridden by the global "disableRepoOverride: true" in the "allstar.yaml" (which also has it set in that sample repo).

**Comment by jeffmendoza** [comment]
Ah thanks for catching that `disableRepoOverride` only applies to repo-level settings of the same policy / file name. The one in allstar.yaml is not a "master" switch. I'll update the docs.

The thinking here is an org-owner may want allstar enabled overall, and some polices forced on, but allow individual repos to opt-out of other policeis, or tweak the expected settings.

**Comment by jeffmendoza** [comment]
I believe this was clarified in #84
