### ISSUE TITLE
Document necessary access rights for repos

### ISSUE THREAD

**Issue by Hixie** [ossf/allstar#65]
It's not immediately clear to me whether I need to give special rights to any particular user for allstar to be able to see the .allstar repo if it's private, or file issues in private repos. The documentation seems to be silent about this. I'm guessing that apps get magic access to everything somehow?

**Comment by jeffmendoza** [comment]
It's mentioned here:
>Install Allstar GitHub App on your organizations and repositories. When installing Allstar, you may review the permissions requested. Allstar asks for read access to most settings and file contents to detect security compliance. It requests write access to issues to create issues, and to checks to allow the block action.

Did you install it? or was it already installed by OSPO? When installing, you select the repos (or all repos), including private, and agree/modify the access given to the app.

**Comment by Hixie** [comment]
OSPO installed it for us as far as I'm aware. Sounds like the answer is that the .allstar repo can be a private repo with nobody (other than repo admins) having access, and it'll work?

**Comment by jeffmendoza** [comment]
Yes, it will.
