### ISSUE TITLE
Upgrade to v3 of scorecard

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/allstar#70]
https://github.com/ossf/allstar/blob/1c2befa6da5151de639ff3145ee95fa64db8ab8b/go.mod#L13

The scorecard version v3 has more reliable features.

**Comment by jeffmendoza** [comment]
Should be done in conjunction with #21

**Comment by naveensrinivasan** [comment]
https://github.com/ossf/scorecard/issues/1273

**Comment by justaugustus** [comment]
Working on this in https://github.com/ossf/allstar/pull/98.

**Comment by justaugustus** [comment]
Fixed in https://github.com/ossf/allstar/pull/101.
