### ISSUE TITLE
Fix the security advisories 

### ISSUE THREAD

**Issue by naveensrinivasan** [ossf/allstar#71]
https://deps.dev/go/github.com%2Fossf%2Fallstar

![image](https://user-images.githubusercontent.com/172697/139553692-9b8f3d49-b0aa-45b8-8342-e149dfbafb94.png)

**Comment by jeffmendoza** [comment]
This is fixed.

**Comment by naveensrinivasan** [comment]
https://deps.dev/go/github.com%2Fossf%2Fallstar

Still has issue

**Comment by jeffmendoza** [comment]
Thanks for checking! Looks like dependabot doesn't catch everything.
Blocked by #70

**Comment by naveensrinivasan** [comment]
Yes, this will get fixed when we upgrade to v3 of scorecard.

**Comment by justaugustus** [comment]
> Thanks for checking! Looks like dependabot doesn't catch everything. Blocked by #70

Should get fixed with https://github.com/ossf/allstar/pull/98.
