### ISSUE TITLE
When is the issue submitted?

### ISSUE THREAD

**Issue by Udomomo** [ossf/allstar#89]
I've created a [sample repository](https://github.com/Udomomo/allstar-sample) to see how Allstar works. It was 9PM JST, and an issue is created in 6AM in the next day.
I couldn't find documents about when Allstar app is triggered. Is it once a day?
Can we configure when it's triggered, or manually trigger?

**Comment by jeffmendoza** [comment]
Hi, thanks for taking a look at allstar. It is currently running in a loop and is taking about 24h to run through all of the installations. I could do some tweaks for more concurrency to get that down, but that isn't my end goal for an architecture.

I have a design and plan to make allstar react to webhooks when something in the repo changes. This would bring down the response time to something much more reasonable. However, it would add a lot of complexity, so I'm not focusing on it at the moment. I'm more focused on features/policies that people are asking for. Hope that helps. =)

**Comment by AkihiroSuda** [comment]
> taking about 24h to run through all of the installations

Could you add this information to the README.md for clarity? 🙏
